# Port configuration
server:
  port: 6063
  ssl:
   key-store-type : PKCS12
   key-store: classpath:ssl/keystore.p12
   key-store-password : ims@ims
   key-alias : ims

spring:
  #Data base configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/tokenbookingapp
    username: hawk
    password: hawk
    driverClassName: org.postgresql.Driver 
  #Jpa Config  
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true   
    
    